tech:
  pyloncompass:
    type: PYLONFINDER
    show_non_running: true
    show_upgrading: true
    update_cooldown: 5s
    tag:
      type: LORE
      lore: Inactive and Upgrading Pylons
      material: COMPASS
  leafshears:
    type: LEAFSHEARS
    clear_cube_size: 3
    cannot_bypass_message: "&cSome of the nearby leaves are reinforced and can't be broken"
    durability_loss_chance: 1.0
    tag:
      type: LORE
      lore: Leaf Burner
      material: SHEARS
  leafshears2:
    type: LEAFSHEARS
    clear_cube_size: 5
    cannot_bypass_message: "&cSome of the nearby leaves are reinforced and can't be broken"
    durability_loss_chance: 1.0
    tag:
      type: LORE
      lore: Leaf Burner II
      material: SHEARS
  testEnchant:
    type: ENCHANT
    enchant: FARSHOT
    effect: FARSHOT

effects:
  type: FARSHOT
  enchant: FARSHOT
  key1: value1

enchantableTypes:
  sword:
    id: SWORD
    materials:
     - DIAMOND_SWORD
     - IRON_SWORD
enchants:
  soulTaker:
    name: Soul Taker
    id: SOUL_TAKER
    maxLevel: 3
    allowedTypes:
     - SWORD
     
anvil:
  repairMaterials:
    emerald:
      item:
        material: EMERALD
      value: 1.0
    emeraldblock:
      item:
        material: EMERALD_BLOCK
      value: 9.0
  materialCosts:
    diamondPick:
      material: DIAMOND_PICKAXE
      value: 6
    diamondSword:
      material: DIAMOND_SWORD
      value: 12
    diamondShovel:
      material: DIAMOND_SPADE
      value: 6
    diamondAxe:
      material: DIAMOND_AXE
      value: 6
    diamondHoe:
      material: DIAMOND_HOE
      value: 6
    diamondHelmet:
      material: DIAMOND_HELMET
      value: 18
    diamondChest:
      material: DIAMOND_CHESTPLATE
      value: 18
    diamondLeggings:
      material: DIAMOND_LEGGINGS
      value: 18
    diamondBoots:
      material: DIAMOND_BOOTS
      value: 18
    ironPick:
      material: IRON_PICKAXE
      value: 2
    ironSword:
      material: IRON_SWORD
      value: 4
    ironShovel:
      material: IRON_SPADE
      value: 2
    ironAxe:
      material: IRON_AXE
      value: 2
    ironHoe:
      material: IRON_HOE
      value: 2
    ironHelmet:
      material: IRON_HELMET
      value: 6
    ironChest:
      material: IRON_CHESTPLATE
      value: 6
    ironLeggings:
      material: IRON_LEGGINGS
      value: 6
    ironBoots:
      material: IRON_BOOTS
      value: 6
    leatherHelmet:
      material: LEATHER_HELMET
      value: 1
    leatherChest:
      material: LEATHER_CHESTPLATE
      value: 1
    leatherLeggings:
      material: LEATHER_LEGGINGS
      value: 1
    leatherBoots:
      material: LEATHER_BOOTS
      value: 1
    stonePick:
      material: STONE_PICKAXE
      value: 1
    stoneSword:
      material: STONE_SWORD
      value: 1
    stoneShovel:
      material: STONE_SPADE
      value: 1
    stoneAxe:
      material: STONE_AXE
      value: 1
    stoneHoe:
      material: STONE_HOE
      value: 1
    goldPick:
      material: GOLD_PICKAXE
      value: 1
    goldSword:
      material: GOLD_SWORD
      value: 1
    goldShovel:
      material: GOLD_SPADE
      value: 1
    goldAxe:
      material: GOLD_AXE
      value: 1
    goldHoe:
      material: GOLD_HOE
      value: 1
    goldHelmet:
      material: GOLD_HELMET
      value: 1
    goldChest:
      material: GOLD_CHESTPLATE
      value: 1
    goldLeggings:
      material: GOLD_LEGGINGS
      value: 1
    goldBoots:
      material: GOLD_BOOTS
      value: 1
    chainmailHelmet:
      material: CHAINMAIL_HELMET
      value: 2
    chainmailChest:
      material: CHAINMAIL_CHESTPLATE
      value: 2
    chainmailLeggings:
      material: CHAINMAIL_LEGGINGS
      value: 2
    chainmailBoots:
      material: CHAINMAIL_BOOTS
      value: 2
    shears:
      material: SHEARS
      value: 2
    shield:
      material: SHIELD
      value: 2
    bow:
      material: BOW
      value: 1
    flintNSteel:
      material: FLINT_AND_STEEL
      value: 1
    rod:
      material: FISHING_ROD
      value: 1
  loreCosts:
    leafshears1:
      lore: Leaf Burner
      value: 1
    leafshears2:
      lore: Leaf Burner II
      value: 2
  enchantCosts:
        fireprot:
          enchant: PROTECTION_FIRE
          value: 3
        flame:
          enchant: ARROW_FIRE
          value: 19
        fireaspect:
          enchant: FIRE_ASPECT
          value: 11
        depthstrider:
          enchant: DEPTH_STRIDER
          value: 5
        respiration:
          enchant: OXYGEN
          value: 4
        frostwalker:
          enchant: FROST_WALKER
          value: 12
        aquaafinity:
          enchant: WATER_WORKER
          value: 6
        featherfalling:
          enchant: PROTECTION_FALL
          value: 4
        baneofarthropods:
          enchant: DAMAGE_ARTHROPODS
          value: 3
        infinity:
          enchant: ARROW_INFINITE
          value: 19
        silktouch:
          enchant: SILK_TOUCH
          value: 12
        protection:
          enchant: PROTECTION_ENVIRONMENTAL
          value: 4
        blastprotection:
          enchant: PROTECTION_EXPLOSIONS
          value: 1
        thorns:
          enchant: THORNS
          value: 2
        power:
          enchant: ARROW_DAMAGE
          value: 8
        projectileprotection:
          enchant: PROTECTION_PROJECTILE
          value: 1
        punch:
          enchant: ARROW_KNOCKBACK
          value: 7
        sharpness:
          enchant: DAMAGE_ALL
          value: 8
        smite:
          enchant: DAMAGE_UNDEAD
          value: 3
        knockback:
          enchant: KNOCKBACK
          value: 7
        efficiency:
          enchant: DIG_SPEED
          value: 2
        unbreaking:
          enchant: DURABILITY
          value: 4
        #Disabled enchants from here onwards
        mending:
          enchant: MENDING
          value: 9999999
        lure:
          enchant: LURE
          value: 9999999
        luckOfTheSea:
          enchant: LUCK
          value: 9999999
        looting:
          enchant: LOOT_BONUS_MOBS
          value: 9999999
        fortune:
          enchant: LOOT_BONUS_BLOCKS
          value: 9999999
  renamingCost: 2.0
  scaleWithMissingDura: true
  blacklistedLore:
   - Compacted Item
